server:
  port: 9113

spring:
  application:
    name: microservice-provider-user1
eureka:
  instance:
      prefer-ip-address: true
  client:
    service-url:
      defaultZone:  http://localhost:8761/eureka/

