server:
  port: 9112

spring:
  application:
    name: microservice-provider-user
eureka:
  instance:
      prefer-ip-address: true
      metadata-map:
        my-metadata:  dfafd
  client:
    service-url:
      defaultZone:  http://peer1:8761/eureka/,http://peer2:8762/eureka/