server:
  port: 9100

  #数据源的配置
spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://localhost:3306/play
    username: root
    password: 123456
mybatis:
  type-aliases-package: com.example.demo.entity
  mapper-locations: classpath:mapper/*.xml

logging:
  level:
    mapper: DEBUG
    com.example.demo: DEBUG